### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by bdbch** [WalshyDev/Discord-Spotify-RPC#1]
It looks like the package.json is missing which causes my `npm start` to break.

Tested on 6.4

**Comment by TheOnlyArtz** [comment]
Hey there, try doing `npm install` and your problem will automatically be solved ;D
- Have good day!

**Comment by Mrtenz** [comment]
`npm install` won't install anything, because of the missing package.json. You should include the package.json as well.

**Comment by TheOnlyArtz** [comment]
Oh yea... I've probably got confused with
`When package.json is there but not package-lock.json`
