### ISSUE TITLE
Error or whatever

### ISSUE THREAD

**Issue by Da532** [WalshyDev/Discord-Spotify-RPC#11]
I understand like **NO** JS, I work in py. 

`{ Error: connect ECONNREFUSED 127.0.0.1:4370
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4370 }`

**Comment by WalshyDev** [comment]
Please follow the setup steps found here: https://github.com/WalshyDev/Discord-Spotify-RPC#setup

**Comment by Da532** [comment]
I've already done everything asked with file edits.

**Comment by WalshyDev** [comment]
According to the error you didn't do the Spotify webhelper one, simply because it states the old port number in the error. Make sure to do that and the second edit. Then you should be good

**Comment by Da532** [comment]
It's changed within the file yet it still defaults to the old port. :/

**Comment by WalshyDev** [comment]
Only thing I can suggest is the file isn't saving, I'm assuming you did extract it and are editing the extracted files not then zip ones?

**Comment by Da532** [comment]
My fault, I installed it to the wrong directory. Thanks for the help!
