### ISSUE TITLE
Create Electron Wrapper to run the Spotify watcher without any CLI knowledge

### ISSUE THREAD

**Issue by bdbch** [WalshyDev/Discord-Spotify-RPC#21]
Since installing NPM, handling with a CLI and setting a npm package up is complicated for people who only want this feature to work, we could consider to have a electron wrapper running to put the script into the tray in the background.

Maybe there is a even less memory heavy solution for that. It's just better for people to run an .exe and get it started.

Then we can also add stuff like "Start on Boot", or customization options for the titles etc.

**Comment by WalshyDev** [comment]
This has been suggested and I'm working on something like it already but with more than just the Spotify Rich Presences. I will leave this issue open for more updates and feedback on this

**Comment by liangchunn** [comment]
I've managed to package the application with minimal footprint on pull request #22 

Currently it compiles for all platforms and is already tested on Windows and macOS.

Electron is a good thing when you need some kind of UI, but is too bloated for what it actually does.
