### ISSUE TITLE
Rich presence only shown locally.

### ISSUE THREAD

**Issue by ottergauze** [WalshyDev/Discord-Spotify-RPC#4]
I've noticed that this script only shows song information to the local client, other users can not see the song information, only the playing status, which shows as the typical `Playing Spotify` message for all viewers of your profile, the rich presence isn't visible.

Additional note: Nothing is logged, everything is displayed as it would be given the script is in working condition. 
```
[19:14:46] Updated RPC rich presence - Reborn - Original Mix
[19:15:01] Updated RPC rich presence - Apollo - Electro Mix
```

**Comment by WalshyDev** [comment]
This seems to be a Discord thing from what I've gathered, sometimes people can see it, others they can't. I'm not fully sure the root cause here, maybe it's multiple people using the same client ID? I'm not sure.

**Comment by ottergauze** [comment]
This may seem a little naive of me, as I haven't done much if at all with Discord's RPC functionality, but is there a way to create your own client ID? Does this have anything to do with Discord's Application dashboard?

Edit: Up to 50 users using the same ID, it seems. Looks like this can be solved by just creating a new custom presence application.

**Comment by WalshyDev** [comment]
Yep just go to https://discordapp.com/applications/me then create one there, once you have it made then you can go down and enable rich presence. After that just upload a Large icon and call it "spotify" then it will work as intended with this little script. Just copy the client Id at the top into the index.js and you should be good to go

**Comment by ottergauze** [comment]
Already got that, don't worry. Cheers for the script, by the way!

**Comment by clrxbl** [comment]
Can confirm this is a Client ID bug thing. Works perfectly fine with a different Client ID
I can't seem to get the icon working tho.

**Comment by ottergauze** [comment]
Side note: You can't add yourself as a tester for a rich presence application. You may have to use an alt.

**Comment by ottergauze** [comment]
> clrxbl: Can confirm this is a Client ID bug thing. Works perfectly fine with a different Client ID, I can't seem to get the icon working tho.

Yep, same issue here. In addition to my previous comment, you dont need to be a tester in order to utilise the rich presence, so I was wrong there.

**Comment by ottergauze** [comment]
**And the problem is still happening.**

**Comment by clrxbl** [comment]
Issue resolved, you have to upload a large image called spotify or change 1 line of code to the name of your image.

https://i.eth0.co/o1v9c9gur6.png

(don't judge me)

**Comment by ottergauze** [comment]
Could you label which line of code this is? I assumed it was line 35 : `largeImageKey: 'spotify',`, but I may have been incorrect.

**Comment by clrxbl** [comment]
Yes, it's that line.

**Comment by clrxbl** [comment]
For example, I have a large asset uploaded with the name "soviet", change the largeImageKey to 'soviet' and it'll change to that asset.

@WalshyDev Consider adding a section to the documentation about creating your own developer application.

**Comment by ottergauze** [comment]
Alright. Well, with that sorted, presence is still showing locally. I'm not entirely sure what to make of this. Checking from my alternate account only shows my Playing status and nothing much else. This seems to just be a complete discord issue.

Additionally, icons are not showing still, even after that change. I uploaded a file by the name of `spotify.png`, and setting the image key to `spotify` or `spotify.png` results in nothing.

**Comment by clrxbl** [comment]
Okay so, apparently my friends no longer see the Rich Presence anymore.

**Comment by WalshyDev** [comment]
@LivingAutoMode Did you make sure to upload it as a "Large" asset and also make sure to press the "Upload Asset" button it's quite small and I didn't see it the first time. Also the image can't be transparent from what I saw and it will show a black image.

**Comment by ottergauze** [comment]
@WalshyDev Cheers. I seemed to have missed that, I also had no idea it let you upload multiple assets so that may come into use at some point :p 

So I'm assuming this issue with the presence only showing locally is a Discord issue out of your control?

**Comment by WalshyDev** [comment]
It is sadly, but I have made it easier for you guys to add your own applications now. Check the README for new config values. You can do something like
```json
{
    "clientId": "<your-application>",
    "largeImageKey": "soviet",
    "largeImageText": "Some text",
    "time": "song-time"
}
```
@LivingAutoMode @clrxbl

**Comment by ottergauze** [comment]
Alright. Cheers. I'll close the issue now as it is marked as a Discord bug and doesn't appear to be patchable.
Cheers for the help in the other regards, though.

**Comment by mcao** [comment]
I have done an investigation into this, and found that because Discord is developing their own Spotify integration, and for other reasons, titles of certain well-known programs are blacklisted from being displayed globally. Thus, if you renamed the application on your My Applications panel to something like "Spotify Desktop" or "Spotify Player", it would be able to display globally.

Hope that helps!

**Comment by WalshyDev** [comment]
Thanks to @mcao for the investigation, I have now renamed the application to "Spotify Player" and it appears to be working again.
