### ISSUE TITLE
Set status to "Listening" instead of "Playing"

### ISSUE THREAD

**Issue by franc-ist** [WalshyDev/Discord-Spotify-RPC#7]
e.g. will say `Listening to xyz` instead of `Playing xyz`

**Comment by clrxbl** [comment]
Not possible, rich presence is only available for games.

**Comment by WalshyDev** [comment]
I can't do this sadly, the listening status is only available for bots through the API at the moment. User accounts can't use this therefore I will not implement, also pretty sure Rich Presence itself forces play since it's intended for games.
